/**
 * SidekickGenerator - Deterministic sidekick generation from a seed
 *
 * Your sidekick is generated from your machine identity (hostname + username).
 * The same seed always produces the same species, rarity, and stats — but
 * the name and personality are generated by the LLM on first hatch and stored.
 */

import os from 'os';
import {
    Sidekick, Species, Rarity, SidekickStats, StatKey,
    SPECIES, RARITIES, STAT_KEYS,
} from './SidekickTypes';

// Rarity weights (must sum to 100)
const RARITY_WEIGHTS: Record<Rarity, number> = {
    common:    60,
    uncommon:  25,
    rare:      10,
    epic:       4,
    legendary:  1,
};

// Stat floor by rarity (higher rarity = higher minimum stats)
const RARITY_FLOOR: Record<Rarity, number> = {
    common:    20,
    uncommon:  30,
    rare:      40,
    epic:      55,
    legendary: 70,
};

/** FNV-1a 32-bit hash */
function fnv32a(str: string): number {
    let h = 0x811c9dc5;
    for (let i = 0; i < str.length; i++) {
        h ^= str.charCodeAt(i);
        h = Math.imul(h, 0x01000193) >>> 0;
    }
    return h;
}

/** Linear congruential PRNG seeded with a number */
class SeededRNG {
    private s: number;
    constructor(seed: number) { this.s = seed >>> 0; }

    next(): number {
        this.s = (Math.imul(this.s, 1664525) + 1013904223) >>> 0;
        return this.s / 0x100000000;
    }

    int(min: number, max: number): number {
        return Math.floor(this.next() * (max - min + 1)) + min;
    }

    pick<T>(arr: readonly T[]): T {
        return arr[Math.floor(this.next() * arr.length)];
    }
}

function pickRarity(rng: SeededRNG): Rarity {
    const roll = rng.int(1, 100);
    let cumulative = 0;
    for (const rarity of RARITIES) {
        cumulative += RARITY_WEIGHTS[rarity];
        if (roll <= cumulative) return rarity;
    }
    return 'common';
}

function generateStats(rng: SeededRNG, rarity: Rarity): {
    stats: SidekickStats;
    peakStat: StatKey;
    dumpStat: StatKey;
} {
    const floor = RARITY_FLOOR[rarity];
    const shuffled = [...STAT_KEYS].sort(() => rng.next() - 0.5);
    const peakStat = shuffled[0];
    const dumpStat = shuffled[1];

    const stats = {} as SidekickStats;
    for (const key of STAT_KEYS) {
        if (key === peakStat) {
            stats[key] = rng.int(floor + 40, 100);
        } else if (key === dumpStat) {
            stats[key] = rng.int(1, 15);
        } else {
            stats[key] = rng.int(floor, floor + 40);
        }
    }

    return { stats, peakStat, dumpStat };
}

/** Generate a language affinity from a list of common ones */
function pickLanguageAffinity(rng: SeededRNG): string {
    const langs = [
        'TypeScript', 'Python', 'Rust', 'Go', 'JavaScript',
        'Java', 'C++', 'Swift', 'Kotlin', 'Ruby',
    ];
    return rng.pick(langs);
}

/**
 * Deterministically generate a sidekick from the current machine identity.
 * Name and personality default to empty strings — they are filled in by
 * SidekickManager on first hatch using the LLM.
 */
export function generateSidekick(): Omit<Sidekick, 'name' | 'personality'> {
    const seed = fnv32a(`${os.hostname()}::${os.userInfo().username}`);
    const rng = new SeededRNG(seed);

    const species = rng.pick(SPECIES);
    const rarity = pickRarity(rng);
    const isShiny = rng.next() < 0.01; // 1% shiny chance

    const { stats, peakStat, dumpStat } = generateStats(rng, rarity);
    const languageAffinity = pickLanguageAffinity(rng);
    const now = new Date().toISOString();

    return {
        id: seed.toString(16).padStart(8, '0'),
        species,
        rarity,
        isShiny,
        stats,
        peakStat,
        dumpStat,
        languageAffinity,
        mood: 'happy',
        level: 1,
        xp: 0,
        streak: 0,
        lastSeen: now,
        hatchedAt: now,
    };
}
